server:
  port: 8088 # El puerto público definitivo para Postman o Frontend

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      # Habilita la integración directa con el servidor de descubrimiento
      discovery:
        locator:
          enabled: true
          lower-case-service-name: true # Convierte los IDs de Eureka a minúsculas para las rutas

      # DEFINICIÓN EXPLICITA DE RUTAS
      routes:
        - id: ms-user-auth-register-routes
          uri: lb://MS-USER-AUTH-REGISTER
          predicates:
            - Path=/api/users/**, /api/profile, /api/v1/auth/**, /oauth2/**, /connect/**, /.well-known/**, /login, /login**
        - id: ms-prestamos-routes
          uri: lb://MS-PRESTAMOS
          predicates:
            - Path=/api/v1/prestamos/**, /api/v1/sanciones/**, /api/v1/reservas/**, /api/estadisticas/**
        - id: ms-devoluciones-routes
          uri: lb://MS-DEVOLUCIONES
          predicates:
            - Path=/api/v1/devoluciones/**
        - id: ms-notificaciones-routes
          uri: lb://MS-NOTIFICACIONES
          predicates:
            - Path=/api/v1/notificaciones/**
        - id: ms-catalogo-routes
          uri: lb://MS-CATALOGO
          predicates:
            - Path=/api/catalogo/**

  security:
    oauth2:
      resourceserver:
        jwt:
          # URL del microservicio de autenticación que emite los tokens
          jwk-set-uri: http://localhost:8081/oauth2/jwks

# Configuración para enlazarse a las páginas amarillas de Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    preferIpAddress: true
