server:
  port: 8081
  forward-headers-strategy: framework

spring:
  config:
    import: optional:file:../.env[.properties]

  application:
    name: ms-user-auth-register

  # ==========================================
  # CONFIGURACIÓN DE POSTGRESQL (JPA/HIBERNATE)
  # ==========================================
  datasource:
    url: ${BIBLIO_DB_URL}
    username: ${BIBLIO_DB_USERNAME}
    password: ${BIBLIO_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: identidad
      maximum-pool-size: ${BIBLIO_DB_POOL_SIZE:5}
      minimum-idle: ${BIBLIO_DB_MIN_IDLE:1}
      connection-timeout: 10000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # Hibernate creará las tablas en Postgres basándose en tus entidades Java
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        default_schema: identidad
        format_sql: true

# AÑADE ESTE BLOQUE DE EUREKA:
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/ # La URL de tus páginas amarillas
  instance:
    preferIpAddress: true # Recomendado para entornos Docker/WSL para evitar problemas de DNS

  # ==========================================
  # CONFIGURACIÓN DE REDIS CACHE
  # ==========================================
  data:
    redis:
      host: 127.0.0.1
      port: 6379
