spring.application.name=ms-devoluciones
server.port=8084

spring.config.import=optional:file:../.env[.properties]

spring.datasource.url=${BIBLIO_DB_URL}
spring.datasource.username=${BIBLIO_DB_USERNAME}
spring.datasource.password=${BIBLIO_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/oauth2/jwks

eureka.client.service-url.defaultZone=http://127.0.0.1:8761/eureka/
eureka.instance.prefer-ip-address=true
